export const UPDATE_USERNAME = 'User/UPDATE_USERNAME'

export const GET_REPOSITORIES = 'User/GET_REPOSITORIES'
export const GET_REPOSITORIES_SUCCESS = 'User/GET_REPOSITORIES_SUCCESS'
export const GET_REPOSITORIES_FAILURE = 'User/GET_REPOSITORIES_FAILURE'

export const GET_USER_INFO = 'User/GET_USER_INFO'
export const GET_USER_INFO_SUCCESS = 'User/GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_FAILURE = 'User/GET_USER_INFO_FAILURE'
